name: Echo Workflow

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Read AWS Policy JSON File
      id: read_file  
      run: |
        echo "content=$(<./policy.json)" >> $GITHUB_ENV

    - name: Run a one-line script
      run: |
        echo "JSON File Content=$content"
